#
name: Delete package

on: [workflow_dispatch]
permissions:
  packages: write
  contents: read

jobs:
  # This pushes the image to GitHub Packages.
  delete-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'publish-packages/game'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN}}
